services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: youruser
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
