services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerCommand: "n8n start"
    healthCheckPath: /healthz
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: youruser
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n.onrender.com
      - key: N8N_API_HOST
        value: 0.0.0.0
      - key: N8N_API_PORT
        value: "5678"
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: your-db-host
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: your-db-name
      - key: DB_POSTGRESDB_USER
        value: your-db-user
      - key: DB_POSTGRESDB_PASSWORD
        value: your-db-password
